# Generated by Django 5.0.6 on 2024-05-17 21:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_itempedido_subtotal_alter_pagamento_troco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_patch),
        ),
    ]
