# Generated by Django 5.0.6 on 2024-05-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itemcardapio_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
