# Generated by Django 5.0.6 on 2024-05-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingrediente_produto_remove_itemcardapio_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcardapio',
            name='produtos',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
